server:
  host: "0.0.0.0"
  port: 9999
  debug: true

model:
  name: "iic/SenseVoiceSmall"
  device: "cuda:0"
  trust_remote_code: true

audio:
  max_file_size_mb: 500
  max_duration_minutes: 120
  supported_formats: ["wav", "mp3", "m4a", "flac", "aac"]
  temp_dir: "./temp"
  segment_length: 10.0
  overlap_length: 2.0
  target_sample_rate: 16000
  target_channels: 1

# 独立的嵌套配置块
audio_preprocessing:
  target_sample_rate: 16000
  target_channels: 1
  target_format: "wav"
  enable_noise_reduction: true
  enable_normalization: true
  silence_threshold_db: -40.0

audio_segmentation:
  segment_length_seconds: 10.0
  overlap_seconds: 2.0
  min_segment_length: 3.0
  max_silence_length: 1.0
  fade_duration: 0.1

streaming:
  batch_size: 128                    # 重要：修复字段名
  batch_timeout_ms: 200
  first_segment_priority: 10
  normal_segment_priority: 1
  max_queue_size: 1000
  queue_check_interval_ms: 50
  max_concurrent_batches: 2
  gpu_memory_threshold: 0.9
  enable_performance_monitoring: true

processing:
  timeout_seconds: 1800
  max_concurrent_tasks: 10
  chunk_size_mb: 1

monitoring:
  enable_metrics: true
  metrics_interval_seconds: 30
  log_batch_performance: true
