server:
  host: "0.0.0.0"
  port: 9999
  debug: true

model:
  name: "iic/SenseVoiceSmall"
  device: "cuda:0"
  trust_remote_code: true

audio:
  max_file_size_mb: 500
  supported_formats: ["wav", "mp3", "m4a", "flac", "aac"]
  temp_dir: "./temp"
  
  # 简化的切片配置
  segment_length: 10.0    # 10秒切片
  overlap_length: 2.0     # 2秒重叠
  target_sample_rate: 16000
  target_channels: 1      # 单声道即可

processing:
  timeout_seconds: 1800
  chunk_size_mb: 1        # 流式处理块大小