server:
  host: "0.0.0.0"
  port: 9999
  debug: true

model:
  name: "iic/SenseVoiceSmall"
  device: "cuda:0"
  trust_remote_code: true

audio:
  max_file_size_mb: 200
  max_duration_minutes: 120
  supported_formats: ["wav", "mp3", "m4a", "flac", "aac"]
  temp_dir: "./temp"

# 嵌套配置保持原有结构
audio_preprocessing:
  target_sample_rate: 16000
  target_channels: 2
  target_format: "wav"
  enable_noise_reduction: true
  enable_normalization: true
  silence_threshold_db: -40

audio_segmentation:
  segment_length_seconds: 10.0
  overlap_seconds: 2.0
  min_segment_length: 3.0
  max_silence_length: 1.0
  fade_duration: 0.1

processing:
  timeout_seconds: 600
  max_concurrent_tasks: 10
